#!/bin/sh
#$ -l mem_free=30G
#$ -l h_vmem=50G
#$ -pe smp 1

fileIndex=$1
savePath=$2
export PATH=$PATH:/common/bermanblab/build/homer/bin

TCGA_IC_A6RE_T2=TCGA_ATACseq/EAC_TCGA-IC-A6RE_T2.bw
TCGA_IG_A4QS_T2=TCGA_ATACseq/EAC_TCGA-IG-A4QS_T2.bw
TCGA_IG_A7DP_T2=TCGA_ATACseq/EAC_TCGA-IG-A7DP_T2.bw
TCGA_L5_A4OE_T2=TCGA_ATACseq/EAC_TCGA-L5-A4OE_T2.bw
TCGA_L7_A6VZ_T2=TCGA_ATACseq/EAC_TCGA-L7-A6VZ_T2.bw
TCGA_M9_A5M8_T2=TCGA_ATACseq/EAC_TCGA-M9-A5M8_T2.bw
TCGA_IG_A3YA_T2=TCGA_ATACseq/ESCC_TCGA-IG-A3YA_T2.bw
TCGA_IG_A4P3_T2=TCGA_ATACseq/ESCC_TCGA-IG-A4P3_T2.bw
TCGA_IG_A51D_T2=TCGA_ATACseq/ESCC_TCGA-IG-A51D_T2.bw
TCGA_IG_A625_T2=TCGA_ATACseq/ESCC_TCGA-IG-A625_T2.bw
TCGA_LN_A49O_T2=TCGA_ATACseq/ESCC_TCGA-LN-A49O_T2.bw
TCGA_LN_A49W_T2=TCGA_ATACseq/ESCC_TCGA-LN-A49W_T2.bw
TCGA_LN_A4A2_T2=TCGA_ATACseq/ESCC_TCGA-LN-A4A2_T2.bw
TCGA_LN_A4A5_T2=TCGA_ATACseq/ESCC_TCGA-LN-A4A5_T2.bw
TCGA_LN_A4MR_T2=TCGA_ATACseq/ESCC_TCGA-LN-A4MR_T2.bw
TCGA_LN_A7HX_T2=TCGA_ATACseq/ESCC_TCGA-LN-A7HX_T2.bw
TCGA_LN_A8HZ_T2=TCGA_ATACseq/ESCC_TCGA-LN-A8HZ_T2.bw
TCGA_LN_A9FQ_T2=TCGA_ATACseq/ESCC_TCGA-LN-A9FQ_T2.bw

/hpc/home/zhengy2/.local/bin/computeMatrix scale-regions -S ${TCGA_IC_A6RE_T2} ${TCGA_IG_A4QS_T2} ${TCGA_IG_A7DP_T2} ${TCGA_L5_A4OE_T2} ${TCGA_L7_A6VZ_T2} \
  ${TCGA_M9_A5M8_T2} ${TCGA_IG_A3YA_T2} ${TCGA_IG_A4P3_T2} ${TCGA_IG_A51D_T2} ${TCGA_IG_A625_T2} ${TCGA_LN_A49O_T2} ${TCGA_LN_A49W_T2} ${TCGA_LN_A4A2_T2} \
  ${TCGA_LN_A4A5_T2} ${TCGA_LN_A4MR_T2} ${TCGA_LN_A7HX_T2} ${TCGA_LN_A8HZ_T2} ${TCGA_LN_A9FQ_T2} \
    -R Data/Figure5CD_S3GH/${fileIndex}.bed --skipZeros --numberOfProcessors 4 --outFileName ${savePath}/${fileIndex}.TCGA_ATAC.pValue.gz \
    --outFileNameMatrix ${savePath}/${fileIndex}.TCGA_ATAC.pValue.tab --outFileSortedRegions ${savePath}/${fileIndex}_sort.TCGA_ATAC.pValue.bed
